'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=localhost\SQLEXPRESS;Initial Catalog=pharmacy;User ID=thienphat;Passw"& _ 
            "ord=thienphat;TrustServerCertificate=True")>  _
        Public ReadOnly Property pharmacySQLConnectionString() As String
            Get
                Return CType(Me("pharmacySQLConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=factManagement;Persist Security Info=True;U"& _ 
            "ser ID=thienphat;Password=chauhue")>  _
        Public ReadOnly Property factManagementConnectionString() As String
            Get
                Return CType(Me("factManagementConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=posprinter;Persist Security Info=True;User "& _ 
            "ID=thienphat;Password=chauhue")>  _
        Public ReadOnly Property posprinterConnectionString() As String
            Get
                Return CType(Me("posprinterConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property pharmacySQLConnectionStringUserOverride() As String
            Get
                Return CType(Me("pharmacySQLConnectionStringUserOverride"),String)
            End Get
            Set
                Me("pharmacySQLConnectionStringUserOverride") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property factManagementConnectionStringUserOverride() As String
            Get
                Return CType(Me("factManagementConnectionStringUserOverride"),String)
            End Get
            Set
                Me("factManagementConnectionStringUserOverride") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property posprinterConnectionStringUserOverride() As String
            Get
                Return CType(Me("posprinterConnectionStringUserOverride"),String)
            End Get
            Set
                Me("posprinterConnectionStringUserOverride") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property setting_dbName_01() As String
            Get
                Return CType(Me("setting_dbName_01"),String)
            End Get
            Set
                Me("setting_dbName_01") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property setting_dbName_02() As String
            Get
                Return CType(Me("setting_dbName_02"),String)
            End Get
            Set
                Me("setting_dbName_02") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property setting_dbName_03() As String
            Get
                Return CType(Me("setting_dbName_03"),String)
            End Get
            Set
                Me("setting_dbName_03") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property setting_dbLogin() As String
            Get
                Return CType(Me("setting_dbLogin"),String)
            End Get
            Set
                Me("setting_dbLogin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property setting_dbPass() As String
            Get
                Return CType(Me("setting_dbPass"),String)
            End Get
            Set
                Me("setting_dbPass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property setting_dbSource() As String
            Get
                Return CType(Me("setting_dbSource"),String)
            End Get
            Set
                Me("setting_dbSource") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("vi")>  _
        Public Property setting_sysLang() As String
            Get
                Return CType(Me("setting_sysLang"),String)
            End Get
            Set
                Me("setting_sysLang") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property setting_printer_MySelf() As Boolean
            Get
                Return CType(Me("setting_printer_MySelf"),Boolean)
            End Get
            Set
                Me("setting_printer_MySelf") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property setting_printer_Name() As String
            Get
                Return CType(Me("setting_printer_Name"),String)
            End Get
            Set
                Me("setting_printer_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property setting_printer_Logo_Opt_01() As Boolean
            Get
                Return CType(Me("setting_printer_Logo_Opt_01"),Boolean)
            End Get
            Set
                Me("setting_printer_Logo_Opt_01") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("285")>  _
        Public Property setting_printer_Logo_Opt_02() As String
            Get
                Return CType(Me("setting_printer_Logo_Opt_02"),String)
            End Get
            Set
                Me("setting_printer_Logo_Opt_02") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property setting_printer_Logo_Opt_03() As String
            Get
                Return CType(Me("setting_printer_Logo_Opt_03"),String)
            End Get
            Set
                Me("setting_printer_Logo_Opt_03") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\Resources\Logo.bmp")>  _
        Public Property setting_printer_Logo_Opt_04() As String
            Get
                Return CType(Me("setting_printer_Logo_Opt_04"),String)
            End Get
            Set
                Me("setting_printer_Logo_Opt_04") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("47")>  _
        Public Property setting_printer_Line_Opt_01() As String
            Get
                Return CType(Me("setting_printer_Line_Opt_01"),String)
            End Get
            Set
                Me("setting_printer_Line_Opt_01") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Courier New")>  _
        Public Property setting_printer_Line_Opt_02() As String
            Get
                Return CType(Me("setting_printer_Line_Opt_02"),String)
            End Get
            Set
                Me("setting_printer_Line_Opt_02") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property setting_printer_Line_Opt_03() As String
            Get
                Return CType(Me("setting_printer_Line_Opt_03"),String)
            End Get
            Set
                Me("setting_printer_Line_Opt_03") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.MyApplication.My.MySettings
            Get
                Return Global.MyApplication.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
